import 'dart:io';

import 'package:path/path.dart' as path;
import 'package:yaml/yaml.dart';

/// Utility class for handling pubspec-related operations
/// Contains methods for naming conventions, file validation, and dependency resolution
class PubspecUtils {
  static final flavorRegExp = RegExp(r'^[\w\d_-]+$');
  static final flavorPubspecRegExp = RegExp(r'pubspec-(?<flavor>[\w]+)\.yaml');
  static final flavorMergedPubspecRegExp = RegExp(
    r'pubspec-(?<flavor>[\w]+)\.g\.yaml',
  );

  static const flavorGroupName = 'flavor';

  static const pubspecName = 'pubspec.yaml';

  static const basePubspecName = 'pubspec-base.yaml';

  static final mergedPubspecNameHeader = '''# Generated by PSM.
# Do not edit this file manually.

''';

  static const dependsOnKey = 'depends_on';

  /// Validates if the given flavor name matches the required format
  static bool checkFlavorName(String flavor) {
    return flavorRegExp.hasMatch(flavor);
  }

  /// Returns the filename for a pubspec file corresponding to the given flavor
  static String getPubspecNameByFlavor(String flavor) {
    return 'pubspec-$flavor.yaml';
  }

  /// Returns the filename for a merged pubspec file corresponding to the given flavor
  static String getMergePubspecNameByFlavor(String flavor) {
    return 'pubspec-$flavor.g.yaml';
  }

  /// Extracts the flavor name from a pubspec filename
  /// Returns an empty string if the filename doesn't match the expected pattern
  static String getFlavorFromPubspecName(String pubspecName) {
    final match = flavorPubspecRegExp.firstMatch(pubspecName);
    if (match != null) {
      return match.namedGroup(flavorGroupName)!;
    }
    return '';
  }

  /// Extracts the flavor name from a merged pubspec filename
  /// Returns an empty string if the filename doesn't match the expected pattern
  static String getFlavorFromMergedPubspecName(String pubspecName) {
    final match = flavorMergedPubspecRegExp.firstMatch(pubspecName);
    if (match != null) {
      return match.namedGroup(flavorGroupName)!;
    }
    return '';
  }

  /// Deletes all merged pubspec files in the given directory
  static void deleteMergedPubspecFiles(Directory directory) {
    for (final file in directory.listSync(recursive: false)) {
      if (file is File) {
        final flavor = PubspecUtils.getFlavorFromMergedPubspecName(
          path.basename(file.path),
        );
        if (flavor.isNotEmpty) {
          file.deleteSync();
        }
      }
    }
  }

  /// Gets the dependency chain for a given pubspec file
  /// Resolves the 'depends_on' relationships recursively
  static List<String> getDependencyFromPubspecName(String filename) {
    final filenames = <String>[];

    void findParent() {
      final currentFilename = filenames.last;
      final currentFile = File(currentFilename);
      if (!currentFile.existsSync()) {
        return;
      }
      final YamlNode node;
      try {
        node = loadYamlNode(currentFile.readAsStringSync());
      } catch (_) {
        return;
      }
      if (node is! YamlMap) {
        return;
      }
      final parentFilename = node[PubspecUtils.dependsOnKey]?.toString();
      if (parentFilename == null) {
        return;
      }
      if (filenames.contains(parentFilename)) {
        filenames.add(parentFilename);
        return;
      }
      filenames.add(parentFilename);
      findParent();
    }

    filenames.add(filename);
    findParent();

    return filenames;
  }
}
