import 'dart:io';

import 'package:path/path.dart' as path;
import 'package:yaml/yaml.dart';

class PubspecUtils {
  static final flavorPubspecRegExp = RegExp(r'pubspec-(?<flavor>[\w]+)\.yaml');
  static final flavorMergedPubspecRegExp = RegExp(
    r'pubspec-(?<flavor>[\w]+)\.g\.yaml',
  );

  static const flavorGroupName = 'flavor';

  static const pubspecName = 'pubspec.yaml';

  static const basePubspecName = 'pubspec-base.yaml';

  static final mergedPubspecNameHeader = '''# Generated by PSM.
# Do not edit this file manually.

''';

  static const dependsOnKey = 'depends_on';

  static String getPubspecNameByFlavor(String flavor) {
    return 'pubspec-$flavor.yaml';
  }

  static String getMergePubspecNameByFlavor(String flavor) {
    return 'pubspec-$flavor.g.yaml';
  }

  static String getFlavorFromPubspecName(String pubspecName) {
    final match = flavorPubspecRegExp.firstMatch(pubspecName);
    if (match != null) {
      return match.namedGroup(flavorGroupName)!;
    }
    return '';
  }

  static String getFlavorFromMergedPubspecName(String pubspecName) {
    final match = flavorMergedPubspecRegExp.firstMatch(pubspecName);
    if (match != null) {
      return match.namedGroup(flavorGroupName)!;
    }
    return '';
  }

  static void deleteMergedPubspecFiles(Directory directory) {
    for (final file in directory.listSync(recursive: false)) {
      if (file is File) {
        final flavor = PubspecUtils.getFlavorFromMergedPubspecName(
          path.basename(file.path),
        );
        if (flavor.isNotEmpty) {
          file.deleteSync();
        }
      }
    }
  }

  static List<String> getDependencyFromPubspecName(String filename) {
    final filenames = <String>[];

    void findParent() {
      final currentFilename = filenames.last;
      final currentFile = File(currentFilename);
      if (!currentFile.existsSync()) {
        return;
      }
      final YamlNode node;
      try {
        node = loadYamlNode(currentFile.readAsStringSync());
      } catch (_) {
        return;
      }
      if (node is! YamlMap) {
        return;
      }
      final parentFilename = node[PubspecUtils.dependsOnKey]?.toString();
      if (parentFilename == null) {
        return;
      }
      if (filenames.contains(parentFilename)) {
        filenames.add(parentFilename);
        return;
      }
      filenames.add(parentFilename);
      findParent();
    }

    filenames.add(filename);
    findParent();

    return filenames;
  }
}
